---
sudo: false
language: ruby
cache: bundler
env:
rvm:
- jruby-1.7.25
matrix:
  include:
    - rvm: jruby-9.1.12.0
      env: LOGSTASH_BRANCH=master
    - rvm: jruby-9.1.12.0
      env: LOGSTASH_BRANCH=6.x
    - rvm: jruby-1.7.25
      env: LOGSTASH_BRANCH=5.6
    - rvm: jruby-1.7.25
      env: LOGSTASH_BRANCH=5.5
    - rvm: jruby-1.7.25
      env: LOGSTASH_BRANCH=5.4
    - rvm: jruby-1.7.25
      env: LOGSTASH_BRANCH=5.3
    - rvm: jruby-1.7.25
      env: LOGSTASH_BRANCH=5.2
    - rvm: jruby-1.7.25
      env: LOGSTASH_BRANCH=5.1
    - rvm: jruby-1.7.25
      env: LOGSTASH_BRANCH=5.0
  allow_failures:
    - rvm: jruby-9.1.12.0
  fast_finish: true
install: true
script: ci/build.sh
jdk: oraclejdk8
